/**
 * Seed data for projects showcase.
 * High production dummy projects across different creative categories with working YouTube video IDs
 * and self-hosted direct video files.
 */
export const INITIAL_PROJECTS = [
  {
    id: '1',
    title: 'HYPERION: Chrono Velocity',
    category: 'Commercial',
    video_type: 'youtube',
    description: 'A dynamic automotive commercial shot across the Swiss Alps, fusing high-speed precision tracking vehicles with high-energy sound design and kinetic typography. Designed for broadcast and international digital campaign.',
    client: 'Apex Automotive',
    role: 'Director & Lead Editor',
    duration: '01:45',
    video_url: 'https://www.youtube.com/watch?v=ScMzIvxBSi4', // Tears of Steel open film 4K
    thumbnail_url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80',
    tags: ['Automotive', 'Color Grading', 'Sound Design', 'High Speed'],
    technologies: ['DaVinci Resolve Studio', 'RED V-Raptor 8K', 'ARRI Signature Primes', 'After Effects'],
    views: 14820,
    featured: true,
    created_at: '2025-11-15T10:00:00.000Z',
  },
  {
    id: '2',
    title: 'Neon Odyssey // Cyber Soundscape',
    category: 'Music Video',
    video_type: 'youtube',
    description: 'Official music video featuring surreal neon cyberpunk aesthetics, volumetric atmospheric fog, and synchronized kinetic editing that ebbs and flows with bass drops and electronic melodies.',
    client: 'Ghost Light Records',
    role: 'Cinematographer & Colorist',
    duration: '03:52',
    video_url: 'https://www.youtube.com/watch?v=aqz-KE-bpKQ', // Big Buck Bunny 4K 60fps
    thumbnail_url: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80',
    tags: ['Music Video', 'Cyberpunk', 'Volumetric', 'Neon'],
    technologies: ['Sony FX9', 'Cooke Anamorphic /i', 'DaVinci Resolve', 'Premiere Pro'],
    views: 38450,
    featured: true,
    created_at: '2025-10-28T14:30:00.000Z',
  },
  {
    id: '3',
    title: 'The Silent Canvas: Whispers of the Arctic',
    category: 'Documentary',
    video_type: 'youtube',
    description: 'An intimate 4K environmental documentary exploring fragile glacial landscapes and the researchers monitoring deep permafrost changes in Svalbard, Norway. Shot on location over 24 continuous sub-zero days.',
    client: 'Nordic Geo Expeditions',
    role: 'Director & Camera Operator',
    duration: '12:15',
    video_url: 'https://www.youtube.com/watch?v=L_LUpnjgPso', // Sintel open movie
    thumbnail_url: 'https://images.unsplash.com/photo-1483921020237-2ff51e8e4b22?auto=format&fit=crop&w=1200&q=80',
    tags: ['Documentary', 'Nature', 'Arctic', 'Cinematic Drone'],
    technologies: ['RED Komodo 6K', 'DJI Inspire 3 (X9-8K Air)', 'Ambient Audio Capture'],
    views: 22190,
    featured: false,
    created_at: '2025-09-12T09:15:00.000Z',
  },
  {
    id: '4',
    title: 'Aethelgard: The Last Sentinel',
    category: 'Short Film',
    video_type: 'youtube',
    description: 'A moody, cinematic dark fantasy short film following an ancient guardian tasked with defending an ethereal mountain shrine from an encroaching void. Premiered at Sitges Film Festival.',
    client: 'Midnight Moon Studios',
    role: 'Director & Visual Effects Supervisor',
    duration: '08:40',
    video_url: 'https://www.youtube.com/watch?v=mDO8g9P6xLg', // Sprite Fright open film
    thumbnail_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80',
    tags: ['Narrative', 'VFX', 'Fantasy', 'Anamorphic'],
    technologies: ['ARRI Alexa Mini LF', 'Atlas Orion 2x Anamorphic', 'Blender', 'Nuke'],
    views: 45600,
    featured: true,
    created_at: '2025-08-04T18:00:00.000Z',
  },
  {
    id: '5',
    title: 'SYNAPSE: Neural Architecture Showcase',
    category: 'Motion Graphics',
    video_type: 'upload', // Demonstrating uploaded HTML5 video playback
    description: 'Self-hosted 4K direct master exploring futuristic quantum computing and biological neural networks through procedural geometry, caustic glass refraction, and iridescent lighting.',
    client: 'Tensor Core Labs',
    role: 'Motion Designer & 3D Artist',
    duration: '01:20',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
    tags: ['3D Motion', 'Procedural', 'Houdini', 'Octane Render', 'Direct Video'],
    technologies: ['Cinema 4D', 'SideFX Houdini', 'Redshift 3D', 'After Effects'],
    views: 18340,
    featured: false,
    created_at: '2025-07-19T11:45:00.000Z',
  },
  {
    id: '6',
    title: 'VOGUE: Solstice Noir Fashion Film',
    category: 'Commercial',
    video_type: 'youtube',
    description: 'Avant-garde fashion editorial film exploring juxtaposition of brutalist architecture with haute couture flowing silks. Utilizing dramatic chiaroscuro high-contrast lighting and 120fps slow-motion capture.',
    client: 'Maison Éthéré',
    role: 'Director of Photography',
    duration: '02:10',
    video_url: 'https://www.youtube.com/watch?v=R6MlUcmOul8', // Charge - Blender Open Movie
    thumbnail_url: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?auto=format&fit=crop&w=1200&q=80',
    tags: ['Fashion', 'Editorial', 'High Contrast', 'Slow Motion'],
    technologies: ['Phantom Flex4K', 'Angenieux Optimo Zooms', 'Astera Titan Tubes'],
    views: 29750,
    featured: false,
    created_at: '2025-06-30T16:20:00.000Z',
  },
  {
    id: '7',
    title: 'Above the Mist: Patagonian Horizons',
    category: 'Commercial',
    video_type: 'youtube',
    description: 'Ultra high-definition aerial journey across the towering granite peaks of Torres del Paine, showcasing extreme altitude FPV drone piloting and stabilized cinema gimbal footage.',
    client: 'Patagonia Outdoor Gear',
    role: 'Aerial Cinematographer',
    duration: '03:15',
    video_url: 'https://www.youtube.com/watch?v=ysz5S6PUM-U', // 4K Nature Cinematography
    thumbnail_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
    tags: ['Aerial', 'Drone', 'FPV', 'Landscape'],
    technologies: ['Custom 7-inch CineLifter', 'RED Komodo', 'DJI Mavic 3 Cine ProRes'],
    views: 31200,
    featured: true,
    created_at: '2025-05-14T08:00:00.000Z',
  },
  {
    id: '8',
    title: 'KROMA: Audio-Reactive Brand System',
    category: 'Motion Graphics',
    video_type: 'youtube',
    description: 'Dynamic brand identity system and kinetic design package created for a premier electronic music festival. Generative visuals respond in real-time to musical frequencies and live crowd inputs.',
    client: 'KROMA Festival Tokyo',
    role: 'Creative Director',
    duration: '01:50',
    video_url: 'https://www.youtube.com/watch?v=CHFif_y2tyM', // Kinetic Typography & Generative Audio Motion
    thumbnail_url: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80',
    tags: ['Motion Graphics', 'Generative', 'Branding', 'Event Visuals'],
    technologies: ['TouchDesigner', 'Cinema 4D', 'After Effects', 'Notch VFX'],
    views: 16400,
    featured: false,
    created_at: '2025-04-10T12:00:00.000Z',
  }
];

export const CATEGORIES = [
  'All',
  'Commercial',
  'Music Video',
  'Short Film',
  'Motion Graphics',
  'Documentary',
];
